name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Deploy to GitHub Pages
        run: |
          mkdir -p ./public
          cp -r ./2049-FokusCurso-proyecto-inicial/* ./public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
